### ISSUE TITLE
Nuxt reloading sometimes update icon lastMod timestamp

### ISSUE THREAD

**Issue by dawid-pstrak-rmtcfm-com** [MMF-FE/svgicon#141]
Nuxt reloading sometimes update icon lastMod timestamp. Would be nice if there will be option to disable `lastMod` timestamp, becuase when it gets updated, I have to remove it from `git changed files` to not push all icons to repo again with just updated timestamp

**Comment by inouetakuya** [comment]
@dawid-pstrak-rmtcfm-com 

I'm guessing you're using nuxt-svgicon instead of svgicon?

(I searched the svgicon source code, but couldn't find anything called lastMod)

Actually, the build process of nuxt-svgicon is almost the same as that of vue-svgicon, but different.

- https://github.com/dschewchenko/nuxt-svgicon/blob/master/lib/build.ts

Some processes, such as the handling of lastMod, are different.

If you are using nuxt-svgicon and suffering from lastMod, I suggest you prepare your own template.

## Example

nuxt.config.js

```js
{
  // ...
  modules: [
    [
      'nuxt-svgicon',
      {
        tpl: 'nuxt-svgicon.template.txt',
      },
    ],
  ],
}
```

nuxt-svgicon.template.txt

```txt
/* eslint-disable */
/* tslint:disable */
// @ts-ignore
import icon from 'vue-svgicon'
icon.register({
  '${name}': {
    width: ${width},
    height: ${height},
    viewBox: ${viewBox},
    data: '${data}'
  }
})
```

See: https://github.com/dschewchenko/nuxt-svgicon
